root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/atrk ./cmd/main.go"
bin = "./tmp/atrk | jq"
stop_on_error = true

[log]
time = false
main_only = false
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
