---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-atro-xyz-v1alpha1-app
  failurePolicy: Fail
  name: vapp.kb.io
  rules:
  - apiGroups:
    - atro.xyz
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apps
  sideEffects: None
