# permissions for end users to edit appbases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: atrk
    app.kubernetes.io/managed-by: kustomize
  name: appbase-editor-role
rules:
- apiGroups:
  - atro.xyz
  resources:
  - appbases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - atro.xyz
  resources:
  - appbases/status
  verbs:
  - get
