apiVersion: atro.xyz/v1alpha1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: atrk
    app.kubernetes.io/managed-by: kustomize
  name: app-sample
spec:
  replicas: 2
  # TODO(user): Add fields here
